# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ipass_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ipass_ios
    pod 'Alamofire'
end
